# Generated by Django 3.2 on 2022-04-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='pushed',
            new_name='active',
        ),
    ]
