# Generated by Django 3.2 on 2022-04-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_pushed_booking_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
